### PR TITLE
Split internal SerializeStruct into itself

### PR DESCRIPTION
**Pull request by pickfire**
`SerializeStruct` does not seem to require next_key.

I based this off https://github.com/dtolnay/serde-yaml/blob/93f4d40d04ad2c424a58ba1fa34f55a3d0faab4f/src/ser.rs#L33 while working on https://github.com/dtolnay/serde-yaml/issues/44, maybe this could be applied to serde-json?

CC @dtolnay

### CODE REVIEW

**Comment by sfackler** [comment]
Could you clarify what problem this is solving?

**Comment by pickfire** [comment]
@sfackler The struct will have not have `next_key`, it does not seemed to be used.

**Comment by sfackler** [comment]
Why is that a problem?

**Comment by pickfire** [comment]
@sfackler Wouldn't it be better to remove a variable (garbage) that is not used? It helps to save memory.

Are there any issues with removing a field that is not used?

**Comment by pyfisch** [comment]
Thanks, but I don't think this optimization is needed. I will change `Value` soon anyway so after that I may look into it again.

**Pull request closed without merging**
