### PR TITLE
Update re-exports and improve value

### PR DESCRIPTION
**Pull request by pyfisch**
Only export the [recommended items](https://serde.rs/conventions.html) from the crate root. Are there enough `to_*` and `from_*` functions exported? I think it is ok that the functions for no-std are found in the `ser` and `de` modules.

Rename all the variant names of the CBOR value to reflect the naming from the RFC more closely. Remove the distinction between I64 and U64. Always store values in canonical order. (serializing CBOR in canonical form should work now :tada: ) I removed the value test and access methods like `is_object` and `get_object`. Are they used in real projects? If this is the case I can add them back in.

What do you think?

### CODE REVIEW

**Comment by sfackler** [comment]
LGTM

Might be worth removing the forced canonicalization in the raw streaming serializer in favor of having people serialize into a Value and then write that out instead?

**Comment by pyfisch** [comment]
> Might be worth removing the forced canonicalization in the raw streaming serializer in favor of having people serialize into a Value and then write that out instead?

Yes, the idea is that people who need canonical CBOR documents serialize their data into `Value` and then this is serialized as canonical CBOR with the correct order of keys inside maps.
Which parts of canonicalization would you remove from the streaming serializer? (see also #109)

**Comment by sfackler** [comment]
The part where the struct serializer buffers all of its entries in memory: https://github.com/pyfisch/cbor/blob/master/src/ser.rs#L771

**Comment by pyfisch** [comment]
>The part where the struct serializer buffers all of its entries in memory: https://github.com/pyfisch/cbor/blob/master/src/ser.rs#L771

Oh, I forgot about this. Yes I will remove the buffering.

**Pull request merged**
